version: "3.8"

services:
  PSQL:
    container_name: PSQL
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=qwerty
    networks:
      - mynet

  NATS:
    container_name: NATS
    image: nats-streaming
    networks:
      - mynet

  L0:
    build: ./Исходники
    image: artap-09/l0
    container_name: L0
    environment:
      - PSQL_NAME=postgres
      - PSQL_PASS=qwerty
      - PSQL_HOST=PSQL
      - PSQL_PORT=5432
      - PSQL_DB=l0
    ports:
      - "4969:4969"
    networks:
      - mynet
    
networks:
  mynet:
    name: mynet
    driver: bridge